[phases.setup]
nixPkgs = ['python3', 'gcc']

[phases.build]
cmds = [
  'pip install --user --no-cache-dir -r requirements.txt',
  'python -m compileall .'
]

[phases.install]
nixPkgs = []

[staticAssets]
